name: Python Tests
run-name: Rest API Python Tests
on:
  push:
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python 3.13.2
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.2
      - name: Run Tests
        run: |
             chmod +x -R ${{ github.workspace }}
             pip install --upgrade pip
             pip install -r requirements.txt
             export PYTHONPATH=${PYTHONPATH}:${{ github.workspace }}
             pytest -s tests/part_01/test_users.py --junitxml=results.xml
      - name: Create Test Summary
        uses: test-summary/action@dist
        if: success() || failure()
        with:
          paths: results.xml
        
      - name: Notify Slack - Build Status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: |
            ${{ job.status == 'success' && ':white_tick: Python Tests completed successfully' || ':x: Python Tests failed' }}
            on branch *${{ github.ref_name }}* by *${{ github.actor }}*.
            Details: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>
          SLACK_TITLE: "Build Status: ${{ job.status }}"
      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ":white_tick: Build Success - ${{ github.repository }}"
          html_body: >
            <!DOCTYPE html><html><body><h2>:white_tick: Build Succeeded!</h2>
            <p>Repository: <b>${{ github.repository }}</b></p>
            <p>Commit: <b>${{ github.sha }}</b></p>
            <p>Branch: <b>${{ github.ref_name }}</b></p>
            <p>Check the details on <a href="${{ github.server_url }}/actions">GitHub Actions</a>.</p>
            </body></html>
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
      - name: Send Build Status Email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "${{ job.status == 'success' && ':white_tick: Build Succeeded' || ':x: Build Failed' }} - ${{ github.repository }}"
          html_body: >
            <!DOCTYPE html><html><body>
            <h2>${{ job.status == 'success' && ':white_tick: Build Succeeded' || ':x: Build Failed' }}</h2>
            <p>Repository: <b>${{ github.repository }}</b></p>
            <p>Commit: <b>${{ github.sha }}</b></p>
            <p>Branch: <b>${{ github.ref_name }}</b></p>
            <p>Check the details on <a href="${{ github.server_url }}/actions">GitHub Actions</a>.</p>
            </body></html>
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
